### ISSUE TITLE
onToggle not called when using controlled prop bypassing getTogglerProps etc

### ISSUE THREAD

**Issue by Andarist** [kentcdodds/react-toggled#16]
**Relevant code or config**
https://codesandbox.io/s/x3lrnl90n4

**Problem description:**

`onToggle` might not get called on controlled prop change. This is a problem if we toggle the state based on i.e. redux state

**Possible solution**
Maybe move `onToggle` call in controlled case to `componentDidUpdate`?

**Comment by newyork-anthonyng** [comment]
@Andarist I refactored the code a bit and it works.

See the [CodeSandbox demo here](https://codesandbox.io/s/8zpj51k8)

`onToggle` will get called if you use the provided `setOn`, `setOff`, and `toggle` methods provided in the child function ([see docs here](https://github.com/kentcdodds/react-toggled#children))

**Comment by Andarist** [comment]
Hi!

I know that it works if I use provided setters, but IMHO it should also work I decide not to when using more declarative way of handling logic than imperative set* calls

**Comment by newyork-anthonyng** [comment]
True, I see your point that it'd be nice to have `onToggle` be consistently called (even when the `on` state is controlled).

But I can also see how, whenever `react-toggled` is `controlled`, you could always just add whatever you were going to do in `onToggle` in your own function.

I wonder what others think.

**Comment by kentcdodds** [comment]
Yes, it seems to me that we should be calling `onToggle` either way. I'd definitely accept a PR for this :+1:

**Comment by kentcdodds** [comment]
Also, thanks for chiming in here @newyork-anthonyng!
