### ISSUE TITLE
Multiple toggle variables

### ISSUE THREAD

**Issue by alexluong** [kentcdodds/react-toggled#24]
Hi @kentcdodds,

Thanks for a great component. I really like these utility component that only implement the logic part like `react-toggled` and `downshift`.

As for this component, I'm wondering if you have thought about making a `MultiToggle` of some sort. It'd do everything the `Toggle` is doing, but with more control props (on_1, on_2, etc). Is it something you thought about but decide not to do? Is it an anti-pattern of some sort?

I'm thinking of making something like that and came across this component. I'd be happy to implement it if you think it'd be useful.

**Comment by kentcdodds** [comment]
Hi @alexluong!

I don't think that we'll support that in this component. It's a pretty small and focused component on purpose. Feel free to make a fork that supports multiple values. Thanks!
