### ISSUE TITLE
README appears to be broken

### ISSUE THREAD

**Issue by tansongyang** [kentcdodds/react-toggled#8]
The README appears to be broken:

![tmp](https://user-images.githubusercontent.com/9488719/31559549-0211b43e-b01f-11e7-8ba2-f3b5ba52b7cf.png)

As you can see, the `react-toggled` link seems malformed. I would have changed this myself, but the comments say not to edit that section because it is auto-generated.

**Comment by kentcdodds** [comment]
Yikes. No idea what happened there 😅 
I'll get it fixed. Thanks!

**Comment by kentcdodds** [comment]
Fixed. Thanks!

I think the problem is that there wasn't a pre-existing table of contents when I upgraded to kcd-scripts and when the precommit hook ran to update the README it added a new one and doctoc just doesn't like the way I structure the top of my READMEs I guess 😅 

Thanks again!
